<?php

namespace App\Services;

use App\Entity\Bars;
use Symfony\Component\HttpFoundation\File\File;

class UploadImg
{
    private $directory = NULL;

    public function __construct($directory){
        $this->directory = $directory;
    }

    public function uploadPhoto(Bars $bar)
    {

        $file = $bar->getPhotos();
        $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

        $file->move(
            $this->directory,
            $fileName);

        $bar->setPhotos($fileName);
    }


    public function newFile(Bars $bar){
         $bar->setPhotos(new File($this->directory.'/'.$bar->getPhotos()));
    }

 /**
     * @return string
     */

    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}